-  name: Intsall shipping setup
   hosts: all
   become: true
   vars:
     component: shipping
     schema: true
   tasks:
     - name: nodejs Setup
       ansible.builtin.import_tasks: java.yml









